INSERT INTO properties (address, city, zipcode, bedroom, bathroom, guest, description, price, image )
VALUES
('4221 Atwood Dr', 'Orlando', '32808', '5', '3', '10', 'You will love the place because of the location, the ambiance, and the people. 2 Car garage. Spacious backyard, patio, hammock, movie room and fire pit. Perfect for couples, solo adventures, business travelers, familys and furry friends.', '200',''),
('1249 Balsam Willow Tr', 'Orlando', '32825', '5', '2', '8', 'Great location! Walking distance (5-7 minute leisurely stroll) from house to International Dr. Centrally located allowing quick access. Cute house with all the amenities, fine bedding, and hard wood floors.', '180',''),
('512 Hearthglen Blvd,', 'Winter Garden', '34787', '4', '2', '6', "Modern and minamalist decor with entirely new furniture and bed in a cozy, private loft tucked away in the heart of Orlando. This walkup offers a relaxing and comfortable night's rest after a day spent at the theme parks, concerts, games or conferences.", '160',''),
('1303 Selbydon Way,', 'Winter Garden', '34787', '4', '2', '6', "A beautiful and luxurious place to stay will make you feel at home with the amenities of a resort 4 pools, Gym, very close to amusement parks and with multiple amenities to enjoy ... spacious and comfortable room with private bathroom and large dressing room, with elegant accessories and beautiful furniture , near Universal and Millenia Mall", '130',''),
('240 Sand Key Estates Dr ', 'Clearwater', '33767', '2', '2', '5', "Our home is located in a historic area of Clearwater with a beautiful gazebo at the end of the street, which is sitting on top of the inter-coastal water. A perfect spot to watch a beautiful Clearwater Sunset!", '110',''),
('2550 State Rd. 580 ', 'Clearwater', '33761', '3', '2', '6', "The Porpoise Inn & Suites is situated on World Famous Clearwater Beach! This quaint Florida Charming Boutique Motel offers a perfect beach vacation for your family. Located 2 blocks from the sands of the beach. The Suites are newly renovated with the classy touch of the coastal living style you can enjoy home away from home!", '120',''),
('2900 Swoop Cir', 'Kissimmee', '34741', '3', '2', '6', "Excellent location close to the Disney Parks, Restaurants, Shops and most Orlando Attractions, just minutes from Interstate 4.This Condo is the perfect choice for your occasion.", '150',''),
('2080 Cypress Bay Blvd', 'Kissimmee', '34743', '3', '3', '7', "A great end unit town house with all the amenities you can imagine. Only 6 miles away from Disney World. Club house, gym, pool, tennis court. and platy grounds are only 5 seconds away. High speed wifi, telephone, fully functional kitchen . New paint", '160',''),
('1249 Balsam Willow Trl,', 'Orlando', '32825', '5', '3', '10', "Great location! Walking distance from Walmart, Restaurants, a short ride to Universal Studios, The Mall at Millennia, International Premium Outlets, Downtown Orlando and 20min to Disney, SeaWord, Convention Center and Orlando International Airport.", '200',''),
('11529 Kazimer Dr,', 'Orlando', '32837', '3', '2', '6', "This is a great place in the heart of downtown Orlando near a ton of restaurants, night life, the Dr. Philips center, Amway arena and Lake Eola. Publix is across the street. There is a kitchenette with sink, refrigerator, microwave, dishes, glasses silverware etc. (no stove). Hulu w showtime, Netflix and amazon prime.", '120',''),


